apiVersion: v1
kind: Service
metadata:
  name: mvasilenko-blog-canary-svc
  labels:
    app: mvasilenko-blog-canary
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: mvasilenko-blog-canary
