apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mvasilenko-blog-rolling-update
spec:
  minReadySeconds: 20
  replicas: 2
  template:
    metadata:
      labels:
        app: mvasilenko-blog
    spec:
      containers:
        - name: mvasilenko-blog
          image: mvasilenko/mvasilenko-blog:red
          ports:
            - containerPort: 80
              protocol: TCP
