apiVersion: v1
kind: Service
metadata:
  name: mvasilenko-blog-blue-green-svc
  labels:
    app: mvasilenko-blog-blue-green
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: mvasilenko-blog-blue-green
    color: blue
