apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mvasilenko-blog-green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mvasilenko-blog-blue-green
        color: green
    spec:
      containers:
        - name: mvasilenko-blog
          image: mvasilenko/mvasilenko-blog:green
          ports:
            - containerPort: 80
